language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -U pytest hypothesis-pytest

script:
  - py.test test.py
